name: Notebook 01 -  Extração de dados

on:
  push:
  schedule:
    - cron: '0 15 * * *'  # Executa todos os dias à meia-noite UTC

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt install ghostscript python3-tk - y
        pip install notebook
        pip install nbconvert

    - name: Execute Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute notebooks/01_extracao_dados_vereadores_e_despesas.ipynb

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
