name: Notebook 01 -  Extração de dados

on:
  push:
    branches:
      - main

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install notebook
        pip install nbconvert

    - name: Execute Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute notebooks/01_extracao_dados_vereadores_e_despesas.ipynb --output output.ipynb

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Bot
        author_email: rehzende@hotmail.com
        message: "Update links.json"
        add: 'dados/relatorios/links.json'
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_GITHUB_TOKEN }}
