name: Execute notebook 01 -  Extração de dados

on: 
   schedule:
    - cron: "0 8 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - uses: yaananth/run-notebook@v2
      
      with:
        working-directory: ./notebooks
        notebook: "./01 - extracao_dados_vereadores_e_despesas.ipynb"
        isReport: False
        poll: True
